run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - gosec
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - nilerr
    - nolintlint
    - stylecheck
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true

  gosec:
    excludes:
      - G204  # Subprocess launched with variable
      - G304  # File path provided as taint input

  staticcheck:
    checks: ["all"]

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocritic

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
